### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by bmagyarkuti** [Zoddy/atom-language-ada#1]
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app/src/package.js:565:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app/src/package.js:187:43)
```

**Comment by bmagyarkuti** [comment]
have absolutely no experience with packages, but will look into when I have a little time -- I gather this should be a tirivial fix.
ps.  thanks for the package by the way, this is what brought me to atom!

**Comment by Zoddy** [comment]
thanks for reporting. i think i will fix this tomorrow =)...

**Comment by bmagyarkuti** [comment]
wow, thanks man! I'm very excited to see *this* ![annoying little thing](https://cloud.githubusercontent.com/assets/5933112/6998306/7625aeda-dbdc-11e4-952b-3c3b907c07f0.png) go away^^

**Comment by Zoddy** [comment]
done ;)...

**Comment by bmagyarkuti** [comment]
thanks, tried it and it's working wonderfully!
