### ISSUE TITLE
Deprecation error

### ISSUE THREAD

**Issue by Quonthil** [Zoddy/atom-language-ada#2]
Hi,
I tried to install your package today and Atom raised a deprecation warning.
It said that I should store packages settings into /settings instead of /scoped-packages. Thus I changed manually the name of the folder and it worked but maybe you should change this for the next version.I'm using Atom v0.194.0

Regards

Brice

**Comment by Zoddy** [comment]
thx for reporting this, should be fixed now. 1.1.0 is at atom.io =)...
