### ISSUE TITLE
ada files

### ISSUE THREAD

**Issue by Quonthil** [Zoddy/atom-language-ada#3]
Hi,
when using your package I could see that files with an old ada extension have not been link the your syntax highlighter. 
I modified the code in order to make it run but you should add the extension '.ada' to the set of ada files for your highlighter. (by the way thanks for your work! it is really useful to me!)

Regards,

Brice

**Comment by Zoddy** [comment]
thx for reporting this, should be fixed now. 1.1.0 is at atom.io =)...

**Comment by Quonthil** [comment]
Thanks! I'll check it out soon!! =)
